"""Bounded inert final receipt/source audit; no worker or submitted-code execution."""
from pathlib import Path
from datetime import datetime,timezone
import json,hashlib,base64
from feature_rl.artifacts import ArtifactStore,canonical_json
from feature_rl.contracts import ActorRole,ArtifactRef
root=Path('docs/evidence/M3/cpu-budget');d=json.loads((root/'cap-result.json').read_text());store=ArtifactStore(Path('.feature-rl/research/M3/cpu-budget/cap-1/artifacts'),ActorRole.CONTROLLER)
source_hashes={str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in Path('src/feature_rl/environments').glob('*') if p.is_file()};assert d['source_hashes']==source_hashes
ref=ArtifactRef.model_validate_json(canonical_json(d['result']['evidence']));data=store.get_bytes(ref,max_envelope_bytes=48*1024*1024,max_payload_bytes=32*1024*1024);receipt=json.loads(data);assert receipt==d['execution_evidence']
cid=receipt['record']['container_id'];assert receipt['effective_cpu_seconds']==.05 and receipt['record']['binding']['effective_cpu_seconds']=='0.05'
assert any(x.get('argv',[])[-3:]==['rm','--force',cid] and x['exit_code']==0 for x in receipt['commands'])
assert any(x.get('argv',[])[-2:]==['inspect',cid] and x['exit_code']==1 and cid.encode() in base64.b64decode(x['stderr_b64']) and b'No such object:' in base64.b64decode(x['stderr_b64']) for x in receipt['commands'])
assert d['status']=='passed' and d['remaining_recovery']==[] and all(x['phase']=='removed' for x in d['operation_records']) and (root/'owned-containers.log').read_bytes()==b''
def check(name,command,status):
 p=root/name
 return {'command':command,'exit_status':status,'log':str(p),'log_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'utc_started':datetime.fromtimestamp(p.stat().st_birthtime,timezone.utc).isoformat(),'utc_finished':datetime.fromtimestamp(p.stat().st_mtime,timezone.utc).isoformat(),'timestamp_source':'log filesystem creation/final-write observations'}
r={'created_at':datetime.now(timezone.utc).isoformat(),'source_hashes':source_hashes,'test_hashes':{str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in [Path('tests/test_environment_cpu_budget.py'),Path('tests/test_environments.py')]},'checks':[check('final-tests.log',['env','PYTHONPATH=src','.venv/bin/python','-m','pytest','-q','tests/test_environment_cpu_budget.py','tests/test_environments.py'],0),check('cap.log',['env','PYTHONPATH=src','.venv/bin/python','docs/evidence/M3/cpu-budget/cap_diagnostic.py'],0),check('red-recovery.log',['env','PYTHONPATH=src','.venv/bin/python','-m','pytest','-q','tests/test_environment_cpu_budget.py','-k','storage or recovery_preserves'],1)],'final_result':(root/'final-tests.log').read_text().strip(),'actual_diagnostic':{'effective_cpu_seconds':.05,'observed_cpu_seconds':receipt['maximum_cpu_seconds'],'observed_overrun_seconds':d['observed_cpu_overrun_seconds'],'source_preserved':d['result']['saved_source']==d['initial_saved'],'cleanup_verified':True,'exact_container_id':cid,'receipt_payload_sha256':hashlib.sha256(data).hexdigest()},'audit_repair':'First inline audit assumed every commands entry had argv and raised KeyError on image metadata. Corrected to recognize metadata entries; no product/receipt change or execution rerun.','evidence_files':{str(p):hashlib.sha256(p.read_bytes()).hexdigest() for p in root.iterdir() if p.is_file() and p.name not in ('verification.json','audit.log')},'limitations':'One real synthetic cap request plus qualification; focused CPU doubles cover phase classification. Sample/probe/cleanup overshoot is explicit. No exact kernel aggregate CPU, model/native/history/GPU execution or consumer wiring claim.'}
(root/'verification.json').write_text(json.dumps(r,indent=2)+'\n');print(r['final_result']);print('Actual cap/source/cleanup receipt and current code hashes verified.')
